More progress

diff --git a/package/opt/hassbian/suites/monitor/install b/package/opt/hassbian/suites/monitor/install
--- a/package/opt/hassbian/suites/monitor/install
+++ b/package/opt/hassbian/suites/monitor/install
@@ -1,10 +1,52 @@
 #!/bin/bash
 # 
-# Installation script for Hassbian suite: DuckDNS
+# Installation script for Hassbian suite: Monitor
 #
 
 function install {
+  echo -n "Installing Mosquitto package: "
 
+  echo "Checking the installation..."
+  validation=$(pgrep -f mosquitto)
+  if [ ! -z "${validation}" ]; then
+    echo "Existing Mosquitto install detected. Skipping install of Mosquitto."
+  else
+    echo "Installing Mosquitto"
+    hassbian-config install mosquitto --accept
+  fi
+
+  echo "Creating Monitor folder..."
+  mkdir /opt/monitor || exit
+  cd /opt || exit
+
+  echo "Cloning Monitor git repository"
+  git clone git://github.com/andrewjfreyer/monitor
+
+  echo "Running interactive setup"
+  cd /opt/monitor || exit
+  chmod +x /opt/monitor/monitor.sh || exit
+  bash /opt/monitor/monitor.sh
+
+  echo "Checking the installation..."
+  if [ ! -f /opt/monitor/monitor.sh ]; then
+    validation=""
+  else
+    validation="ok"
+  fi
+
+  if [ ! -z "${validation}" ]; then
+    echo
+    echo -e "\\e[32mInstallation done..\\e[0m"
+    echo -e "Update of mqtt_preferences is required found at /opt/monitor/mqtt_prefences"
+    echo -e "Some further configuration is required and details can be found here https://github.com/andrewjfreyer/monitor#getting-started "
+    echo
+  else
+    echo
+    echo -e "\\e[31mInstallation failed..."
+    echo
+    return 1
+  fi
+  return 0
 }
 
 [[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"
