Done... Mostly...

diff --git a/package/opt/hassbian/suites/razberry/install b/package/opt/hassbian/suites/razberry/install
--- a/package/opt/hassbian/suites/razberry/install
+++ b/package/opt/hassbian/suites/razberry/install
@@ -1,10 +1,34 @@
 #!/bin/bash
 # 
-# Installation script for Hassbian suite: DuckDNS
+# Installation script for Hassbian suite: RaZberry
 #
 
 function install {
+  echo "Checking for version of Raspberry Pi"
+  RPI_BOARD_REVISION=$(grep Revision /proc/cpuinfo | cut -d: -f2 | tr -d " ")
+  if [[ $RPI_BOARD_REVISION ==  "a02082" || $RPI_BOARD_REVISION == "a22082" ]]
+  then
+    echo "Raspberry Pi 3 Detected. Disabling Bluetooth"
+    systemctl disable hciuart
+    if ! grep -q "dtoverlay=pi3-miniuart-bt" /boot/config.txt
+    then
+      echo "Adding 'dtoverlay=pi3-miniuart-bt' to /boot/config.txt"
+      echo "dtoverlay=pi3-miniuart-bt" >> /boot/config.txt
+    fi
+  fi
 
+  validation=$(grep "dtoverlay=pi3-miniuart-bt" /boot/config.txt)
+  if [ ! -z "${validation}" ]; then
+    echo
+    echo -e "\\e[32mInstallation done..\\e[0m"
+    echo
+  else
+    echo
+    echo -e "\\e[31mInstallation failed..."
+    echo
+    return 1
+  fi
+  return 0
 }
 
 [[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"
