more testing stuff

diff --git a/package/opt/hassbian/helpers/developer b/package/opt/hassbian/helpers/developer
--- a/package/opt/hassbian/helpers/developer
+++ b/package/opt/hassbian/helpers/developer
@@ -42,33 +42,44 @@ function hassbian.developer.test.functions {
   # This should only be used by maintainers!
   local pass=0
   local fail=0
+  local skip=0
   local function
-  local functions
   local retruncode
 
-  # Get all functions
-  for function in $(declare -F | grep "hassbian\\."); do
-    function=$(echo "$function" | awk -F' ' '{print $NF}')
-    if [[ "$function" != *".developer."* ]] && [[ "$function" != *".action."* ]] && [[ "$function" = *"."* ]]; then
-      functions+=("$function")
-    fi
-  done
+  echo "
+  ---------------------------------------
+  TESTING HASSBIAN-CONFIG FUNCTIONS
+  ---------------------------------------
+  "
 
-  for function in "${functions[@]}"; do
-    echo -e "\\n\\nTesting $function\\n"
-    "$function"
-    retruncode="$?"
-    echo "$retruncode"
-    if [ "$retruncode" == "0" ];then
-      pass+=1
-    elif [ "$retruncode" == "1" ];then
-      fail+=1
-    else
-      echo -e "\\n\\n------------------------------------------------------\\n"
-      echo "$retruncode is NOT a valid code for $function."
-      echo -e "\\n\\n------------------------------------------------------\\n"
+  for function in $(declare -F | grep "hassbian\\."); do
+    if [[ "$function" = *"."* ]]; then
+      printf "\\e[36mTesting '%s'..............." "$function"
+      if \
+        [[ "$function" = *".developer."* ]] || \
+        [[ "$function" = *".action."* ]] || \
+        [[ "$function" = *".input."* ]] || \
+        [[ "$function" = *".node."* ]]; then
+        skip+=1
+        printf "\\e[33mSKIP\\n"
+      else
+        "$function" >> /dev/null
+        retruncode="$?"
+        if [ "$retruncode" == "0" ];then
+          pass+=1
+          printf "\\e[32mPASS\\n"
+        else
+          fail+=1
+          printf "\\e[31mFAIL\\n"
+        fi
+      fi
     fi
-    sleep 5
   done
+  printf "\\e[0m\\n"
+  echo "
+  Total passed:......$pass
+  Total failed:......$fail
+  Total skiped:......$skip
+  "
 }
 [[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"
