More testing

diff --git a/package/opt/hassbian/helpers/developer b/package/opt/hassbian/helpers/developer
--- a/package/opt/hassbian/helpers/developer
+++ b/package/opt/hassbian/helpers/developer
@@ -37,50 +37,82 @@ function hassbian.developer.test.pr {
   rm -R "$INSTALLDIR"
 }
 
-function hassbian.developer.test.functions {
+function hassbian.developer.test.package {
   # Run a test on all functions.
   # This should only be used by maintainers!
   local pass=0
   local fail=0
   local skip=0
   local function
-  local retruncode
+  local returncode
+  local testsuite=template
 
   echo "
-  ---------------------------------------
+  ------------------------------------------
   TESTING HASSBIAN-CONFIG FUNCTIONS
-  ---------------------------------------
+  ------------------------------------------
   "
 
   for function in $(declare -F | grep "hassbian\\."); do
     if [[ "$function" = *"."* ]]; then
       printf "\\e[36mTesting '%s'..............." "$function"
-      if \
-        [[ "$function" = *".developer."* ]] || \
-        [[ "$function" = *".action."* ]] || \
-        [[ "$function" = *".input."* ]] || \
-        [[ "$function" = *".log.share"* ]] || \
-        [[ "$function" = *".node"* ]]; then
-        skip+=1
+
+      # Exclude functions from tests:
+      if [[ "$function" =~ ^(\
+        hassbian.developer.test.package|\
+        hassbian.developer.test.pr|\
+        hassbian.input.bool|\
+        hassbian.input.info|\
+        hassbian.input.text|\
+        hassbian.log.share|\
+        hassbian.suite.action.execute|\
+        hassbian.suite.action|\
+        hassbian.suite.helper.exist|\
+        hassbian.suite.helper.install.node|\
+        hassbian.suite.info.installed\
+        )$ ]]; then
+        ((skip+=1))
         printf "\\e[33mSKIP\\n"
+
+      # Run tests:
       else
-        "$function" >> /dev/null
-        retruncode="$?"
-        if [ "$retruncode" == "0" ];then
-          pass+=1
+        "$function" >> /dev/null 2>&1
+        returncode="$?"
+        if [ "$returncode" == "0" ];then
+          ((pass+=1))
           printf "\\e[32mPASS\\n"
         else
-          fail+=1
+          ((fail+=1))
           printf "\\e[31mFAIL\\n"
         fi
       fi
     fi
   done
   printf "\\e[0m\\n"
+
+  echo "
+  ------------------------------------------
+  TESTING HASSBIAN-CONFIG SUITE OPERATIONS
+  ------------------------------------------
+  "
+  operations=('show' 'install' 'upgrade' 'remove')
+  for cmd in "${operations[@]}"; do
+    printf "\\e[36mTesting 'hassbian-config %s %s'............." "$cmd" "$testsuite"
+    hassbian-config "$cmd" "$testsuite" >> /dev/null 2>&1
+    returncode="$?"
+    if [ "$returncode" == "0" ];then
+      ((pass+=1))
+      printf "\\e[32mPASS\\n"
+    else
+      ((fail+=1))
+      printf "\\e[31mFAIL\\n"
+    fi
+  done
+
+
   echo "
   Total passed:......$pass
   Total failed:......$fail
-  Total skiped:......$skip
   "
 }
 [[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"
