More cleanup

diff --git a/package/opt/hassbian/helpers/suite/action b/package/opt/hassbian/helpers/suite/action
--- a/package/opt/hassbian/helpers/suite/action
+++ b/package/opt/hassbian/helpers/suite/action
@@ -6,12 +6,9 @@
 declare suitename
 declare suitestate
 declare suiteaction
-declare retrunedvalue
+declare returnvalue
 
 function hassbian.suite.action {
-  # Purpose: Check if a suite exist.
-  # Return 0 if found, else 1.
-
   suiteaction="$1"
   suitename="$2"
 
@@ -42,15 +39,7 @@ function hassbian.suite.action {
 
   # Run the suite action.
   if [[ "$suiteaction" =~ ^(install|upgrade|remove)$ ]]; then
-    if [ -f "$HASSBIAN_SUITE_DIR/$suitename/$suiteaction" ]; then
-      source "$HASSBIAN_SUITE_DIR/$suitename/$suiteaction"
-      "$suiteaction" | tee "$HASSBIAN_LOG_FILE"
-      returnvalue="$?"
-
-      return "$returnvalue"
-    else
-      echo "$suiteaction script does not exist for this suite."
-    fi
+    hassbian.suite.action.execute "$suiteaction" "$suitename" 2>&1 | tee "$HASSBIAN_LOG_FILE"
   else
     echo "$suiteaction is not a valid suite action."
     exit 1
@@ -60,7 +49,7 @@ function hassbian.suite.action {
   if [ "$HASSBIAN_RUNTIME_DEBUG" == true ]; then set +x; fi
 
   # Post action
-  if [ "$retrunedvalue" == "0" ]; then
+  if [ "$returnvalue" == "0" ]; then
     suitestate="installed"
   else
     echo "$ECHO_ACTION_ERROR"
@@ -74,4 +63,16 @@ function hassbian.suite.action {
   fi
 }
 
+function hassbian.suite.action.execute {
+  # We need this extra function to keep logging and be able to use the return value.
+  suiteaction="$1"
+  suitename="$2"
+  if [ -f "$HASSBIAN_SUITE_DIR/$suitename/$suiteaction" ]; then
+    source "$HASSBIAN_SUITE_DIR/$suitename/$suiteaction"
+    "$suiteaction"
+    returnvalue="$?"
+  else
+    echo "$suiteaction script does not exist for this suite."
+  fi
+}
 [[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"
