More progress.

diff --git a/package/opt/hassbian/helpers/suite/helper b/package/opt/hassbian/helpers/suite/helper
--- a/package/opt/hassbian/helpers/suite/helper
+++ b/package/opt/hassbian/helpers/suite/helper
@@ -57,4 +57,77 @@ function hassbian.suite.helper.manifest {
   printf "%s" "$manifestvalue"
 }
 
+function hassbian.suite.helper.blockcheck {
+  # Check the manifest if the suite is blocked.
+  # If blocked, print the message and exit.
+  # Usage:
+  # hassbian.suite.helper.blockcheck [suite]
+  # hassbian.suite.helper.blockcheck duckdns
+  local blocked
+  local blocked_releasename
+  local blocked_message
+  local osrelease
+
+  suitename="$1"
+
+  blocked=$(hassbian.suite.helper.manifest "$suitename" blocked)
+
+  if [ "$blocked" = true ]; then
+    osrelease=$(hassbian.info.version.osreleasename)
+    blocked_releasename=$(hassbian.suite.helper.manifest "$suitename" blocked_releasename)
+    if [ "$blocked_releasename" == "ALL" ] || [ "$blocked_releasename" == "$osrelease" ]; then
+      blocked_message=$(hassbian.suite.helper.manifest "$suitename" blocked_message)
+      printf "%s\\n" "$blocked_message"
+      exit
+    fi
+  fi
+}
+
+
+function hassbian.suite.helper.exist {
+  # Purpose: Check if a suite exist.
+  # Usage:
+  # hassbian.suite.helper.exist [suite]
+  # hassbian.suite.helper.exist duckdns
+
+  suitename="$1"
+
+  # Check if suite name is empty.
+  if [ -z "$suitename" ]; then
+    echo "Suitename cannot be empty."
+    exit 1
+  fi
+
+  # Check if suite directory exist.
+  if [ ! -d "$HASSBIAN_SUITE_DIR/$1" ]; then
+    echo "$suitename does not exist."
+    exit 1
+  else
+
+    # Check if suite manifest file exist.
+    if [ ! -f "$HASSBIAN_SUITE_DIR/$1/manifest" ]; then
+      echo "$suitename are missing manifest file."
+      exit 1
+    fi
+
+    # Check if suite install file exist.
+    if [ ! -f "$HASSBIAN_SUITE_DIR/$1/install" ]; then
+      echo "$suitename are missing install file."
+      exit 1
+    fi
+
+    # Check if suite upgrade file exist.
+    if [ ! -f "$HASSBIAN_SUITE_DIR/$1/upgrade" ]; then
+      echo "$suitename are missing upgrade file."
+      exit 1
+    fi
+
+    # Check if suite remove file exist.
+    if [ ! -f "$HASSBIAN_SUITE_DIR/$1/remove" ]; then
+      echo "$suitename are missing remove file."
+      exit 1
+    fi
+  fi
+}
+
 [[ "$_" == "$0" ]] && echo "$ECHO_HELPER_WARNING"
