Add function and CLI option for developer-test-pr

diff --git a/package/usr/local/bin/hassbian-config b/package/usr/local/bin/hassbian-config
--- a/package/usr/local/bin/hassbian-config
+++ b/package/usr/local/bin/hassbian-config
@@ -102,6 +102,29 @@ function check-permission {
   return 0
 }
 
+function developer-test-pr { # This function fetches a active PR and build a installation package from that and install it on the system.
+    # This should only be used by maintainers to test PR's!
+    readonly PRNUMBER="$1"
+    readonly INSTALLDIR="/tmp/hassbian_config_install_${PRNUMBER}"
+    if [[ -z "$PRNUMBER" ]]; then
+        echo "Error: Missing PR argument."
+        echo ""
+        echo "Run: bash test_pr.sh PRNUMBER"
+        return 1
+    fi
+    git clone https://github.com/home-assistant/hassbian-scripts.git "$INSTALLDIR"
+    cd "$INSTALLDIR" || return 1
+    git fetch origin +refs/pull/"$PRNUMBER"/merge || return 1
+    git checkout FETCH_HEAD
+
+    chmod 755 -R package
+    dpkg-deb --build package/
+    apt install -y "$INSTALLDIR"/package.deb --reinstall --allow-downgrades
+
+    cd || return 1
+    rm -r "$INSTALLDIR"
+}
+
 function raspberry_pi_zero_check {
 ## Start check for Raspberry Pi Zero
 if [ "$FORCE" != "true" ]; then
@@ -305,6 +328,11 @@ case $COMMAND in
     else
       RUN="echo suite $SUITE doesn't exist."
     fi
+    shift # past argument
+    shift # past value
+    ;;
+  "developer-test-pr")
+    RUN="developer-test-pr $2"
     shift # past argument
     shift # past value
     ;;
