Check for permissions on where needed

diff --git a/package/usr/local/bin/hassbian-config b/package/usr/local/bin/hassbian-config
--- a/package/usr/local/bin/hassbian-config
+++ b/package/usr/local/bin/hassbian-config
@@ -101,8 +101,17 @@ function get-suites-from-db {
    echo $suites
 }
 
+function check-permission {
+   if (( $EUID != 0 ))
+   then
+      echo "Error: hassbian-config must be as root (with sudo)"
+      exit 1
+   fi
+}
+
 function install-suite {
    # Having got here, the installer script exists; source it, then run the installer function.
+   check-permission
    update-suite-state "$1" "installing"
    source $SUITE_INSTALL_DIR/install_$1.sh
    if $1-install-package
@@ -115,6 +124,7 @@ function install-suite {
 
 function upgrade-suite {
    # Having got here, the installer script exists; source it, then run the installer function.
+   check-permission
    update-suite-state "$1" "upgrading"
    source $SUITE_INSTALL_DIR/upgrade_$1.sh
    if $1-upgrade-package
